CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806171838_InitialCreate') THEN
    CREATE TABLE "Players" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "KeycloakId" text NOT NULL,
        "Name" text NOT NULL,
        "Ranking" integer NOT NULL,
        "PreferredCue" text,
        "ProfilePictureUrl" text NOT NULL,
        CONSTRAINT "PK_Players" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806171838_InitialCreate') THEN
    CREATE TABLE "Matches" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Player1Id" integer NOT NULL,
        "Player2Id" integer NOT NULL,
        "StartTime" timestamp with time zone NOT NULL,
        "EndTime" timestamp with time zone,
        "WinnerId" integer,
        "TableNumber" integer,
        CONSTRAINT "PK_Matches" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Matches_Players_Player1Id" FOREIGN KEY ("Player1Id") REFERENCES "Players" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Matches_Players_Player2Id" FOREIGN KEY ("Player2Id") REFERENCES "Players" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Matches_Players_WinnerId" FOREIGN KEY ("WinnerId") REFERENCES "Players" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806171838_InitialCreate') THEN
    CREATE INDEX "IX_Matches_Player1Id" ON "Matches" ("Player1Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806171838_InitialCreate') THEN
    CREATE INDEX "IX_Matches_Player2Id" ON "Matches" ("Player2Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806171838_InitialCreate') THEN
    CREATE INDEX "IX_Matches_WinnerId" ON "Matches" ("WinnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806171838_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Players_KeycloakId" ON "Players" ("KeycloakId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260806171838_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260806171838_InitialCreate', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260810012148_AddStartTimeIndex') THEN
    CREATE INDEX "IX_Matches_StartTime" ON "Matches" ("StartTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260810012148_AddStartTimeIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260810012148_AddStartTimeIndex', '10.0.10');
    END IF;
END $EF$;
COMMIT;

